version: 2

models:
  - name: films
    description: "Films table in the destination database"
    columns:
      - name: film_id
        description: "Unique identifier for each film"
        tests:
          - not_null
          - unique
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released"
        tests:
          - not_null
      - name: price
        description: "Price of the film"
        tests:
          - not_null
      - name: rating
        description: "Rating of the film"
        tests:
          - not_null
      - name: user_rating
        description: "User rating of the film"
        tests:
          - not_null

  - name: actors
    description: "Actors table in the destination database"
    columns:
      - name: actor_id
        description: "Unique identifier for each actor"
        tests:
          - not_null
          - unique
      - name: name
        description: "Name of the actor"
        tests:
          - not_null

  - name: film_actors
    description: "Film actors table in the destination database"
    columns:
      - name: film_id
        description: "Unique identifier for each film"
        tests:
          - not_null
      - name: actor_id
        description: "Unique identifier for each actor"
        tests:
          - not_null

  - name: film_ratings
    description: "Film ratings table in the destination database"
    columns:
      - name: film_id
        description: "Unique identifier for each film"
        tests:
          - not_null
          - unique
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released"
        tests:
          - not_null
      - name: price
        description: "Price of the film"
        tests:
          - not_null
      - name: rating
        description: "Rating of the film"
      - name: user_rating
        description: "User rating of the film"
        tests:
          - not_null
      - name: actor_count
        description: "Number of actors in the film"
        tests:
          - not_null
      - name: average_actor_rating
        description: "Average rating of actors in the film"
        tests:
          - not_null
